//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobsPizza.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public decimal Small { get; set; }
        public decimal Medium { get; set; }
        public decimal Large { get; set; }
        public decimal Regular { get; set; }
        public decimal Thin { get; set; }
        public decimal Thick { get; set; }
        public decimal Sausage { get; set; }
        public decimal Pepperoni { get; set; }
        public decimal Onions { get; set; }
        public decimal GreenPeppers { get; set; }
    }
}
